// ─── IMAGES ────────────────────────────────────────────────────────────────
// Each image uses a gradient overlay + Unsplash photo blend for reliability
export const IMAGES = {
  hero:        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=90',
  marseille:   'https://images.unsplash.com/photo-1565726134135-55e78d43e47f?auto=format&fit=crop&w=1200&q=80',
  sanary:      'https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?auto=format&fit=crop&w=1200&q=80',
  aix:         'https://images.unsplash.com/photo-1600091169823-a128c8c18d1b?auto=format&fit=crop&w=1200&q=80',
  toulon:      'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?auto=format&fit=crop&w=1200&q=80',
  calanques:   'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=1200&q=80',
  verdon:      'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?auto=format&fit=crop&w=1200&q=80',
  porquerolles:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
  valensole:   'https://images.unsplash.com/photo-1499889808931-317a4a5b61c3?auto=format&fit=crop&w=1200&q=80',
  lesbaux:     'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?auto=format&fit=crop&w=1200&q=80',
  stremy:      'https://images.unsplash.com/photo-1519449556851-5720b33024e7?auto=format&fit=crop&w=1200&q=80',
  avignon:     'https://images.unsplash.com/photo-1591992335851-6669ee7fca5f?auto=format&fit=crop&w=1200&q=80',
  cassis:      'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=1200&q=80',
  wedding:     'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80',
  munich:      'https://images.unsplash.com/photo-1595867818082-083862f3d630?auto=format&fit=crop&w=1200&q=80',
  lavender:    'https://images.unsplash.com/photo-1499889808931-317a4a5b61c3?auto=format&fit=crop&w=1200&q=80',
}

// ─── FLIGHTS ───────────────────────────────────────────────────────────────
export const FLIGHTS = {
  outbound: {
    date: 'July 14–15, 2026',
    route: 'San Diego → Marseille',
    totalDuration: '14h 55m',
    stops: '1 stop',
    class: 'Economy Light',
    capitalOneConf: 'H-N-KRJX58',
    lufthansaConf: 'A6GLFR',
    legs: [
      { flight: 'LH 467', from: 'San Diego', fromCode: 'SAN', to: 'Munich', toCode: 'MUC', departs: 'Jul 14 · 5:15 PM', arrives: 'Jul 15 · 1:25 PM', duration: '11h 10m' },
      { flight: 'LH 2264', from: 'Munich', fromCode: 'MUC', to: 'Marseille', toCode: 'MRS', departs: 'Jul 15 · 3:25 PM', arrives: 'Jul 15 · 5:10 PM', duration: '1h 45m', layover: '2h layover in Munich' },
    ],
  },
  return: {
    date: 'August 2, 2026',
    route: 'Munich → San Diego',
    totalDuration: '11h 45m',
    stops: 'Nonstop',
    class: 'Economy Light',
    legs: [
      { flight: 'LH 466', from: 'Munich', fromCode: 'MUC', to: 'San Diego', toCode: 'SAN', departs: 'Aug 2 · 12:40 PM', arrives: 'Aug 2 · 3:25 PM', duration: '11h 45m' },
    ],
  },
}

// ─── ITINERARY ─────────────────────────────────────────────────────────────
export const ITINERARY = [
  {
    date: '2026-07-14', label: 'Tue Jul 14', location: 'San Diego → Munich', region: 'travel',
    activities: [
      { time: '5:15 PM', title: 'Depart SAN', detail: 'LH 467 to Munich — 11h 10m', type: 'flight' },
      { time: 'In-flight', title: 'Overnight flight', detail: 'Arrive Munich Jul 15 at 1:25 PM local time', type: 'travel' },
    ],
    notes: 'Pack snacks. Download offline Google Maps for Marseille & Toulon. Euros from ATM on arrival.',
  },
  {
    date: '2026-07-15', label: 'Wed Jul 15', location: 'Munich → Marseille · Endoume', region: 'marseille',
    activities: [
      { time: '1:25 PM', title: 'Land Munich (MUC)', detail: '2h layover — Terminal 2', type: 'flight' },
      { time: '3:25 PM', title: 'LH 2264 → Marseille', detail: '1h 45m flight', type: 'flight' },
      { time: '5:10 PM', title: 'Arrive Marseille (MRS)', detail: 'Uber to Endoume ~20 min, ~€30', type: 'transport' },
      { time: 'Evening', title: 'Corniche Kennedy walk', detail: 'Easy sunset stroll along the sea — perfect for jet lag', type: 'activity' },
      { time: 'Dinner', title: 'Vallon des Auffes', detail: 'Rosé and light dinner at the tiny fishermen\'s harbor', type: 'food' },
    ],
    notes: 'Jet lag day — keep it simple. In bed by 10 PM local time.',
  },
  {
    date: '2026-07-16', label: 'Thu Jul 16', location: 'Marseille · Endoume', region: 'marseille',
    activities: [
      { time: 'Morning', title: 'MuCEM + Fort Saint-Jean', detail: 'Book tickets online in advance — peak season queues', type: 'activity' },
      { time: 'Midday', title: 'Le Panier', detail: 'Oldest district — street art, Marseille soap shops, terrace cafés', type: 'activity' },
      { time: 'Afternoon', title: 'Parc Valmer', detail: 'Shaded paths and bay views — good for the heat', type: 'activity' },
      { time: 'Dinner', title: 'Chez Fonfon', detail: 'Legendary bouillabaisse at Vallon des Auffes — book ahead', type: 'food' },
    ],
    notes: 'Walk before noon or after 6 PM — July hits 30–33°C. Book MuCEM at mucem.org.',
  },
  {
    date: '2026-07-17', label: 'Fri Jul 17', location: 'Aix day trip → Sanary-sur-Mer', region: 'aix',
    activities: [
      { time: 'Morning', title: 'Aix-en-Provence', detail: 'TER train from Marseille St-Charles (~35 min). Cours Mirabeau market, Vieil Aix, Cézanne atelier', type: 'activity' },
      { time: 'Afternoon', title: 'Travel to Sanary', detail: 'Train to Bandol then taxi ~10 min, or train to Toulon + taxi west. Total ~1h', type: 'transport' },
      { time: 'Evening', title: 'Sanary port', detail: 'Summer nightly craft market 7:30 PM–1 AM along the harbor', type: 'activity' },
    ],
    notes: 'Check out of Endoume Airbnb. Store bags at Marseille St-Charles station if needed (consigne automatique).',
  },
  {
    date: '2026-07-18', label: 'Sat Jul 18', location: 'Sanary → Toulon', region: 'toulon',
    activities: [
      { time: 'Morning', title: 'Île de Bendor', detail: '7-min ferry from Sanary port. Beach, art gallery, wine museum — Paul Ricard\'s island', type: 'activity' },
      { time: 'Midday', title: 'Travel to Toulon', detail: 'Taxi Sanary → Toulon ~25 min, ~€35. Check in to hotel.', type: 'transport' },
      { time: 'Afternoon', title: 'Mont Faron', detail: 'Télécabine (cable car) for panoramic views over Toulon bay', type: 'activity' },
      { time: 'Evening', title: 'Old Toulon dinner', detail: 'Cours Lafayette area — early night before the wedding', type: 'food' },
    ],
    notes: 'Pre-book 3:30 AM taxi from Résidence du Cap Brun for Sunday night TONIGHT. Do not forget.',
  },
  {
    date: '2026-07-19', label: 'Sun Jul 19', location: 'Toulon · The Wedding 💍', region: 'wedding',
    activities: [
      { time: '5:00–5:45 PM', title: 'Arrivals & Welcome', detail: 'Résidence du Cap Brun, 198 Chemin Lieutenant Aviateur Paul Gayraud', type: 'wedding' },
      { time: '6:00 PM', title: 'Ceremony', detail: 'Dress code: Riviera Chic — no stiletto heels (gravel paths)', type: 'wedding' },
      { time: '6:30 PM', title: 'Welcome Reception', detail: '', type: 'wedding' },
      { time: '8:30 PM', title: 'Seated Dinner', detail: '', type: 'wedding' },
      { time: '9:30 PM', title: 'Party', detail: 'Until 3:30 AM — pre-booked taxi for the return!', type: 'wedding' },
    ],
    notes: 'Paula & Sébastien\'s wedding. Riviera Chic dress code. Taxi home pre-booked.',
  },
  {
    date: '2026-07-20', label: 'Mon Jul 20', location: 'Sanary-sur-Mer · Cassis', region: 'sanary',
    activities: [
      { time: '11:00 AM', title: 'Wedding Brunch', detail: '57 Impasse Pierchas, Sanary-sur-Mer — casual summer attire, hat + sunscreen', type: 'wedding' },
      { time: 'Afternoon', title: 'Cassis + Calanques', detail: 'Boat tour of the Calanques from Cassis port — book in advance', type: 'activity' },
    ],
    notes: 'Proposed by Sébastien. Comfortable shoes for brunch — cobblestones.',
  },
  {
    date: '2026-07-21', label: 'Tue Jul 21', location: 'Sanary · Cassis · Calanques', region: 'sanary',
    activities: [
      { time: '9:00–1:00 PM', title: 'Boat Trip in Sanary', detail: 'Sébastien organized — 4-hour morning boat trip', type: 'activity' },
      { time: 'Afternoon', title: 'Cassis & Calanques', detail: 'Calanque d\'En-Vau hike or kayak — most dramatic canyon in the park', type: 'activity' },
    ],
    notes: 'Bring sunscreen, water, swimsuit. Boat trip is Sébastien\'s plan — confirm details with him.',
  },
  {
    date: '2026-07-22', label: 'Wed Jul 22', location: 'Porquerolles Day Trip', region: 'porquerolles',
    activities: [
      { time: 'Morning', title: 'Ferry to Porquerolles', detail: 'Take the ferry from La Tour Fondue (Hyères) — ~20 min crossing', type: 'transport' },
      { time: 'All day', title: 'Porquerolles Island', detail: 'Plage Notre-Dame, cycling trails, turquoise swimming. Car-free island.', type: 'activity' },
      { time: 'Evening', title: 'Ferry back', detail: 'Last ferry back to La Tour Fondue — check schedule', type: 'transport' },
    ],
    notes: 'Sébastien\'s suggestion: "Ideal for a 1 day trip — need to take the ferry." Book ferry in advance in July.',
  },
  {
    date: '2026-07-23', label: 'Thu Jul 23', location: 'Les Baux-de-Provence', region: 'lesbaux',
    activities: [
      { time: 'Morning', title: 'Les Baux-de-Provence', detail: 'Medieval citadel ruins, Alpilles mountain views, Carrières des Lumières art show', type: 'activity' },
      { time: 'Afternoon', title: 'Explore the Alpilles', detail: 'Dramatic limestone landscape around Les Baux — great for walks', type: 'activity' },
    ],
    notes: 'Rent a car for flexibility in this area — public transport is sparse.',
  },
  {
    date: '2026-07-24', label: 'Fri Jul 24', location: 'St-Rémy-de-Provence', region: 'stremy',
    activities: [
      { time: 'Morning', title: 'Saint-Paul de Mausole', detail: 'The monastery where Van Gogh spent a year — Gallo-Roman ruins of Glanum nearby', type: 'activity' },
      { time: 'Afternoon', title: 'St-Rémy village', detail: 'Sophisticated Provençal village — markets, cafés, antiques', type: 'activity' },
    ],
    notes: 'Van Gogh\'s haven. Buy local olive oil and calissons.',
  },
  {
    date: '2026-07-25', label: 'Sat Jul 25', location: 'Avignon', region: 'avignon',
    activities: [
      { time: 'Morning', title: 'Palais des Papes', detail: 'Largest Gothic palace in Europe — UNESCO heritage site', type: 'activity' },
      { time: 'Afternoon', title: 'Pont d\'Avignon + ramparts', detail: 'Medieval walls, bridge views, old city walk', type: 'activity' },
      { time: 'Evening', title: 'Festival d\'Avignon', detail: 'July = world-famous theater festival — check program at festival-avignon.com', type: 'activity' },
    ],
    notes: 'Avignon is Loup\'s hometown — reach out for local tips!',
  },
  {
    date: '2026-07-26', label: 'Sun Jul 26', location: 'Aix-en-Provence', region: 'aix',
    activities: [
      { time: 'Morning', title: 'Aix market day', detail: 'Sunday market on Cours Mirabeau — best of the week', type: 'activity' },
      { time: 'Afternoon', title: 'Mazarin District', detail: '17th-century mansions, fountains, galleries', type: 'activity' },
      { time: 'Evening', title: 'Dinner in Aix', detail: 'Final night in Provence — find a good terrace restaurant on Cours Mirabeau', type: 'food' },
    ],
    notes: 'Last full day in Provence. Soak it in.',
  },
  {
    date: '2026-07-27', label: 'Mon Jul 27', location: 'Verdon Gorge', region: 'verdon',
    activities: [
      { time: 'Morning', title: 'Gorges du Verdon', detail: '25km gorge — kayak or electric boat on the turquoise water', type: 'activity' },
      { time: 'Afternoon', title: 'Lac de Sainte-Croix', detail: 'Gateway lake to the gorge — stunning views, paddleboards for rent', type: 'activity' },
    ],
    notes: 'Need a car to access Verdon. Book kayak/boat rental in advance for July.',
  },
  {
    date: '2026-07-28', label: 'Tue Jul 28', location: 'South of France → Munich', region: 'travel',
    activities: [
      { time: 'Morning', title: 'Depart south of France', detail: 'Head to Marseille or Nice airport, or TGV to Paris then Munich', type: 'transport' },
      { time: 'Afternoon', title: 'Travel to Munich', detail: 'Options: fly MRS→MUC, or TGV Paris→Munich (~3.5h from Paris)', type: 'transport' },
      { time: 'Evening', title: 'Arrive Munich', detail: 'Check in — 4 nights in Munich before the flight home', type: 'transport' },
    ],
    notes: 'Need to book France→Munich transport. Flight departs Munich Aug 2 at 12:40 PM.',
  },
  {
    date: '2026-07-29', label: 'Wed Jul 29', location: 'Munich, Germany', region: 'munich',
    activities: [
      { time: 'All day', title: 'Explore Munich', detail: 'Marienplatz, English Garden, beer halls, Viktualienmarkt', type: 'activity' },
    ],
    notes: '',
  },
  {
    date: '2026-07-30', label: 'Thu Jul 30', location: 'Munich, Germany', region: 'munich',
    activities: [
      { time: 'All day', title: 'Day trip options', detail: 'Neuschwanstein Castle (2h), Salzburg (1.5h), Dachau Memorial', type: 'activity' },
    ],
    notes: '',
  },
  {
    date: '2026-07-31', label: 'Fri Jul 31', location: 'Munich, Germany', region: 'munich',
    activities: [
      { time: 'All day', title: 'Museums + Nymphenburg', detail: 'Deutsches Museum, BMW World, Nymphenburg Palace gardens', type: 'activity' },
    ],
    notes: '',
  },
  {
    date: '2026-08-01', label: 'Sat Aug 1', location: 'Munich, Germany', region: 'munich',
    activities: [
      { time: 'All day', title: 'Last day in Munich', detail: 'Easy day — pack, last beer garden, Isar River walk', type: 'activity' },
      { time: 'Evening', title: 'Pack + early night', detail: 'Flight tomorrow at 12:40 PM — check in online opens today', type: 'travel' },
    ],
    notes: 'Check in for LH466 opens Aug 1 ~12:40 PM. Pack tonight.',
  },
  {
    date: '2026-08-02', label: 'Sun Aug 2', location: 'Munich → San Diego ✈️', region: 'travel',
    activities: [
      { time: '12:40 PM', title: 'Depart Munich (MUC)', detail: 'LH 466 nonstop to San Diego — 11h 45m', type: 'flight' },
      { time: '3:25 PM', title: 'Arrive San Diego (SAN)', detail: 'Same day arrival — welcome home!', type: 'flight' },
    ],
    notes: 'Conf: A6GLFR. Check in via Lufthansa app.',
  },
]

// ─── REGION CONFIG ─────────────────────────────────────────────────────────
export const REGIONS = {
  travel:      { label: 'Travel Day',   color: 'bg-slate-500',       text: 'text-slate-700',  border: 'border-slate-300',  img: IMAGES.hero },
  marseille:   { label: 'Marseille',    color: 'bg-teal-600',        text: 'text-teal-700',   border: 'border-teal-300',   img: IMAGES.marseille },
  aix:         { label: 'Aix',          color: 'bg-plovender',       text: 'text-purple-700', border: 'border-purple-300', img: IMAGES.aix },
  toulon:      { label: 'Toulon',       color: 'bg-pblue',           text: 'text-blue-700',   border: 'border-blue-300',   img: IMAGES.toulon },
  wedding:     { label: 'Wedding Day',  color: 'bg-pgold',           text: 'text-amber-700',  border: 'border-amber-300',  img: IMAGES.wedding },
  sanary:      { label: 'Sanary',       color: 'bg-pterracotta',     text: 'text-orange-700', border: 'border-orange-300', img: IMAGES.sanary },
  porquerolles:{ label: 'Porquerolles', color: 'bg-cyan-500',        text: 'text-cyan-700',   border: 'border-cyan-300',   img: IMAGES.porquerolles },
  lesbaux:     { label: 'Les Baux',     color: 'bg-stone-500',       text: 'text-stone-700',  border: 'border-stone-300',  img: IMAGES.lesbaux },
  stremy:      { label: 'St-Rémy',      color: 'bg-polive',          text: 'text-green-700',  border: 'border-green-300',  img: IMAGES.stremy },
  avignon:     { label: 'Avignon',      color: 'bg-rose-600',        text: 'text-rose-700',   border: 'border-rose-300',   img: IMAGES.avignon },
  verdon:      { label: 'Verdon',       color: 'bg-emerald-600',     text: 'text-emerald-700',border: 'border-emerald-300',img: IMAGES.verdon },
  munich:      { label: 'Munich',       color: 'bg-zinc-600',        text: 'text-zinc-700',   border: 'border-zinc-300',   img: IMAGES.munich },
}

// ─── LODGING ───────────────────────────────────────────────────────────────
export const LODGING = [
  {
    id: 'endoume',
    name: 'Sea View Apartment · Anse de Malmousque',
    location: 'Endoume, Marseille',
    region: 'marseille',
    checkIn: 'Jul 15, 2026',
    checkOut: 'Jul 17, 2026',
    nights: 2,
    pricePerNight: 185,
    rating: 4.91,
    reviews: 82,
    status: 'saved',
    link: 'https://www.airbnb.com/wishlists/1969151094',
    notes: 'Already in "The Southern Reach" wishlist. Book ASAP — July is peak season.',
    img: IMAGES.marseille,
    badge: 'Guest Favorite',
  },
  {
    id: 'sanary',
    name: 'TBD · Sanary-sur-Mer',
    location: 'Sanary-sur-Mer',
    region: 'sanary',
    checkIn: 'Jul 17, 2026',
    checkOut: 'Jul 20, 2026',
    nights: 3,
    pricePerNight: null,
    rating: null,
    status: 'searching',
    link: '',
    notes: 'Need to book. Wedding weekend base. Close to brunch venue at 57 Impasse Pierchas.',
    img: IMAGES.sanary,
  },
  {
    id: 'toulon',
    name: 'Hotel near Cap Brun',
    location: 'Toulon',
    region: 'toulon',
    checkIn: 'Jul 18, 2026',
    checkOut: 'Jul 20, 2026',
    nights: 2,
    pricePerNight: null,
    rating: null,
    status: 'searching',
    link: '',
    notes: 'Options: OKKO Hotels Toulon Centre, Best Western Plus La Corniche (5-7 min to venue). Book directly for flex cancellation.',
    img: IMAGES.toulon,
  },
  {
    id: 'provence',
    name: 'TBD · Inland Provence',
    location: 'Les Baux / St-Rémy / Aix area',
    region: 'lesbaux',
    checkIn: 'Jul 23, 2026',
    checkOut: 'Jul 28, 2026',
    nights: 5,
    pricePerNight: null,
    status: 'searching',
    link: '',
    notes: 'Base for Les Baux, St-Rémy, Avignon, Aix, Verdon. Consider a mas (Provençal farmhouse) rental.',
    img: IMAGES.lesbaux,
  },
  {
    id: 'munich',
    name: 'TBD · Munich',
    location: 'Munich, Germany',
    region: 'munich',
    checkIn: 'Jul 28, 2026',
    checkOut: 'Aug 2, 2026',
    nights: 5,
    pricePerNight: null,
    status: 'searching',
    link: '',
    notes: 'Near Munich Hauptbahnhof for easy airport access. Flight departs MUC Aug 2 at 12:40 PM.',
    img: IMAGES.munich,
  },
]

// ─── WEDDING ───────────────────────────────────────────────────────────────
export const WEDDING = {
  couple: 'Paula & Sébastien',
  date: 'Sunday, July 19, 2026',
  venue: 'Résidence du Cap Brun',
  address: '198 Chemin Lieutenant Aviateur Paul Gayraud, 83000 Toulon',
  website: 'https://paula-sebastien.wedsites.com',
  schedule: [
    { time: '5:00–5:45 PM', event: 'Arrivals & Welcome' },
    { time: '6:00 PM',      event: 'Ceremony' },
    { time: '6:30 PM',      event: 'Welcome Reception' },
    { time: '8:30 PM',      event: 'Seated Dinner' },
    { time: '9:30 PM',      event: 'Party begins' },
    { time: '3:30 AM',      event: 'Party ends — pre-booked taxi!' },
  ],
  dresscode: 'Riviera Chic — elegant cocktail attire, seaside-appropriate. No stiletto heels (gravel paths at venue).',
  brunch: {
    date: 'Monday, July 20, 2026',
    time: '11:00 AM',
    address: '57 Impasse Pierchas, 83110 Sanary-sur-Mer',
    attire: 'Casual summer — comfortable shoes, hat, sunscreen',
  },
  hotels: [
    { name: 'OKKO Hotels Toulon Centre', distance: '10–15 min', note: 'Best design/comfort' },
    { name: 'Best Western Plus La Corniche', distance: '5–7 min', note: 'Closest to venue' },
    { name: 'Grand Hôtel Dauphiné', distance: '10–15 min', note: '' },
    { name: 'Ibis Styles Toulon Centre', distance: '10–15 min', note: '' },
    { name: 'Ibis Budget Toulon Centre', distance: '10–15 min', note: 'Budget option' },
    { name: "L'Eautel Toulon Port", distance: '10–15 min', note: '' },
  ],
  postWedding: [
    { day: 'Mon Jul 20', plan: 'Brunch in Sanary (11 AM) + afternoon in Cassis/Calanques' },
    { day: 'Tue Jul 21', plan: 'Boat Trip in Sanary 09:00–13:00 + afternoon Cassis/Calanques' },
    { day: 'Wed Jul 22', plan: 'Porquerolles Day Trip (take the ferry)' },
  ],
}

// ─── NATURE ADVENTURES ─────────────────────────────────────────────────────
export const ADVENTURES = [
  {
    id: 'calanques-boat',
    title: 'Calanques Boat Tour',
    location: 'Cassis',
    region: 'calanques',
    description: 'Spectacular limestone coves accessible only by boat. Calanque d\'En-Vau is the most dramatic. Book a guided boat tour from Cassis port.',
    duration: '2–3 hours',
    difficulty: 'Easy',
    bestTime: 'Morning — calmer seas',
    bookingLink: '',
    img: IMAGES.calanques,
    date: 'Jul 20 or 21',
  },
  {
    id: 'boat-sanary',
    title: 'Boat Trip · Sanary',
    location: 'Sanary-sur-Mer',
    region: 'sanary',
    description: 'Sébastien\'s organized 4-hour morning boat trip. Departs 09:00, returns 13:00.',
    duration: '4 hours',
    difficulty: 'Easy',
    bestTime: '9:00 AM',
    bookingLink: '',
    img: IMAGES.sanary,
    date: 'Tue Jul 21',
    note: 'Organized by Sébastien — confirm details',
  },
  {
    id: 'porquerolles',
    title: 'Porquerolles Island',
    location: 'Île de Porquerolles',
    region: 'porquerolles',
    description: 'Car-free Mediterranean island. White sand Plage Notre-Dame, cycling trails, turquoise swimming. Take the ferry from La Tour Fondue, Hyères.',
    duration: 'Full day',
    difficulty: 'Easy',
    bestTime: 'First ferry of the day',
    bookingLink: '',
    img: IMAGES.porquerolles,
    date: 'Wed Jul 22',
  },
  {
    id: 'verdon',
    title: 'Gorges du Verdon',
    location: 'Var / Alpes-de-Haute-Provence',
    region: 'verdon',
    description: 'Europe\'s Grand Canyon — 25km gorge with mesmerizing turquoise water. Kayak, electric boat, or dramatic cliffside hike.',
    duration: 'Full day',
    difficulty: 'Moderate',
    bestTime: 'Weekday morning',
    bookingLink: '',
    img: IMAGES.verdon,
    date: 'Jul 27',
  },
  {
    id: 'valensole',
    title: 'Valensole Lavender Fields',
    location: 'Valensole Plateau',
    region: 'lavender',
    description: 'The world\'s most photographed lavender blooms — peak season July. Symmetrical purple rows stretching toward the alpine foothills. Sunrise is spectacular.',
    duration: '2–3 hours',
    difficulty: 'Easy',
    bestTime: 'Sunrise or golden hour',
    bookingLink: '',
    img: IMAGES.valensole,
    date: 'Late July',
    note: 'Peak bloom in July — go early morning',
  },
  {
    id: 'mucem',
    title: 'MuCEM + Fort Saint-Jean',
    location: 'Marseille',
    region: 'marseille',
    description: 'Museum of European and Mediterranean Civilisations. Cross the footbridge to Fort Saint-Jean for panoramic terrace views — free. Book online for peak season.',
    duration: '2–3 hours',
    difficulty: 'Easy',
    bestTime: 'Morning, opens 11 AM',
    bookingLink: 'https://www.mucem.org',
    img: IMAGES.marseille,
    date: 'Jul 16',
  },
  {
    id: 'bendor',
    title: 'Île de Bendor',
    location: 'Sanary-sur-Mer',
    region: 'sanary',
    description: 'Paul Ricard\'s island — 7-min ferry from Sanary port. Beach, art gallery, wine and spirits museum. Perfect easy morning.',
    duration: '2–3 hours',
    difficulty: 'Easy',
    bestTime: 'Morning',
    bookingLink: '',
    img: IMAGES.sanary,
    date: 'Jul 18 morning',
  },
  {
    id: 'montfaron',
    title: 'Mont Faron Cable Car',
    location: 'Toulon',
    region: 'toulon',
    description: 'Télécabine ride up Mont Faron for panoramic views over Toulon bay and out to sea. WWII memorial museum at the summit.',
    duration: '2 hours',
    difficulty: 'Easy',
    bestTime: 'Afternoon for views',
    bookingLink: '',
    img: IMAGES.toulon,
    date: 'Jul 18 afternoon',
  },
]

// ─── RESTAURANTS ───────────────────────────────────────────────────────────
export const RESTAURANTS = [
  {
    id: 'fonfon',
    name: 'Chez Fonfon',
    city: 'Marseille',
    region: 'marseille',
    cuisine: 'Provençal · Seafood',
    price: '€€€',
    description: 'Legendary bouillabaisse at Vallon des Auffes — the authentic Marseillais experience.',
    link: '',
    status: 'saved',
  },
  {
    id: 'auffes',
    name: 'Vallon des Auffes bistros',
    city: 'Marseille',
    region: 'marseille',
    cuisine: 'French · Seafood',
    price: '€€',
    description: 'Tiny fishermen\'s harbor with waterfront bistros. Great for arrival dinner or sunset rosé.',
    link: '',
    status: 'saved',
  },
  {
    id: 'sanary-port',
    name: 'Port restaurants · Sanary',
    city: 'Sanary-sur-Mer',
    region: 'sanary',
    cuisine: 'French · Mediterranean',
    price: '€€',
    description: 'Palm-lined harbor restaurants. Fresh fish and rosé with views of the Pointu boats.',
    link: '',
    status: 'saved',
  },
  {
    id: 'aix-cours',
    name: 'Cours Mirabeau terrace',
    city: 'Aix-en-Provence',
    region: 'aix',
    cuisine: 'French · Brasserie',
    price: '€€',
    description: 'Any terrace on Cours Mirabeau for a classic Aix evening under the plane trees.',
    link: '',
    status: 'saved',
  },
  {
    id: 'cassis-quai',
    name: 'Quayside dining · Cassis',
    city: 'Cassis',
    region: 'calanques',
    cuisine: 'Seafood · French',
    price: '€€',
    description: 'Harborfront restaurants in Cassis. Pair with local AOC Cassis white wine.',
    link: '',
    status: 'saved',
  },
]

// ─── BUDGET ────────────────────────────────────────────────────────────────
export const BUDGET = {
  eurUsdRate: 1.08,
  categories: [
    { id: 'flights',    label: 'Flights',        icon: '✈️',  budgetUsd: 2800, actualUsd: 2800, note: 'Paid via Capital One Travel · Round-trip Lufthansa', color: 'bg-pblue' },
    { id: 'lodging',    label: 'Lodging',         icon: '🏠',  budgetUsd: 3500, actualUsd: 0,    note: '19 nights across 5 locations — still booking',      color: 'bg-plovender' },
    { id: 'food',       label: 'Food & Drink',    icon: '🍷',  budgetUsd: 1500, actualUsd: 0,    note: '~€70–100/day for 2 people',                         color: 'bg-pterracotta' },
    { id: 'activities', label: 'Activities',      icon: '⛵',  budgetUsd: 800,  actualUsd: 0,    note: 'Boat trips, MuCEM, cable car, ferry, Calanques',    color: 'bg-polive' },
    { id: 'transport',  label: 'Transport',       icon: '🚂',  budgetUsd: 600,  actualUsd: 0,    note: 'Trains, taxis, Uber, car rental, France→Munich',    color: 'bg-teal-600' },
    { id: 'wedding',    label: 'Wedding Gift',    icon: '💝',  budgetUsd: 300,  actualUsd: 0,    note: 'Honeymoon fund — no registry',                      color: 'bg-pgold' },
    { id: 'shopping',   label: 'Shopping',        icon: '🛍️',  budgetUsd: 500,  actualUsd: 0,    note: 'Souvenirs, olive oil, lavender, wine',              color: 'bg-rose-500' },
    { id: 'misc',       label: 'Misc',            icon: '💰',  budgetUsd: 400,  actualUsd: 0,    note: 'SIM card, international plan, tips, incidentals',   color: 'bg-slate-500' },
  ],
}
